# Generated by Django 3.0.7 on 2020-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('elementary', models.CharField(choices=[('행당', '행당'), ('성수', '성수')], max_length=20)),
            ],
        ),
    ]
